# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
jobs:
  include:
  - os: linux
    dist: bionic
  - os: linux
    dist: xenial
  - os: osx
sudo: false
cache: packages
before_install:
  - sudo apt-get install -y libudunits2-dev
