# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
jobs:
  include:
  - os: linux
    dist: bionic
  - os: linux
    dist: xenial
  - os: osx
sudo: false
install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
before_install:
  - sudo apt-get install -y libudunits2-dev
