# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

jobs:
  include:

  - os: linux
    dist: bionic
    r: release

  - os: linux
    dist: bionic
    r: devel

  - os: linux
    dist: xenial
    r: release

  - os: linux
    dist: xenial
    r: devel

  - os: osx
    r: release

  - os: osx
    r: devel

sudo: false

cache:
  packages: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libudunits2-dev; fi
