---
title: "sandbox"
author: "Joses Ho"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
editor_options: 
  chunk_output_type: inline
---

```{r}
library(dabestr)
```


```{r create-data}
set.seed(54321)

N = 40
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
g1 <- rnorm(N, mean = 120, sd = 25)
g2 <- rnorm(N, mean = 80, sd = 50)
g3 <- rnorm(N, mean = 100, sd = 12)
g4 <- rnorm(N, mean = 100, sd = 50)
gender <- c(rep('Male', N/2), rep('Female', N/2))
id <- 1: N

wide.data <- tibble::tibble(
              Control1 = c1, Control2 = c2,
              Group1 = g1, Group2 = g2, Group3 = g3, Group4 = g4,
              Gender = gender, ID = id)

my.data <- wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Gender)
```


```{r}
aa <- 
  my.data %>%
  dabest(Group, Measurement, 
       
       # # WORKS.
       # idx = c("Control1", "Group1"),
       # paired = FALSE
       
       # # WORKS.
       # # Need to tweak drawing of L-axes? for slopegraph.
       # idx = c("Control1", "Group1"),
       # paired = TRUE, id.col = ID
       
       # # WORKS.
       # idx = list(c("Control2", "Group4"),
       #            c("Control1", "Group1"),
       #            c("Group2", "Group3")),
       # paired = TRUE, id.col = ID
       
       # # WORKS
       # idx = c("Control1", "Group2", "Group4"),
       # paired = FALSE
       
       # WORKS.
       idx = list(c("Control1", "Group1", "Group4"),
                  c("Control2", "Group2", "Group3")),
       paired = FALSE
       )

aa

```


```{r test.plot}

aa <- 
  my.data %>%
  dabest(Group, Measurement, 
       idx = list(c("Control1", "Group1", "Group4"),
                  c("Control2", "Group2", "Group3")),
       paired = FALSE)


plot(aa, color.col = Gender,
     
     rawplot.ylim = c(-100, 200),
     effsize.ylim = c(-60, 60),

     rawplot.ylabel = "rawplot?",
     effsize.ylabel = "MY delta plot!"
     
)

```


