---
title: "explore random number generators between R and Python"
author: "Joses Ho"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r load.libraries}
library(reticulate)
use_condaenv("dabest-dev-py3.7")
```

# RNG in R

According to the documentation for `set.seed()`, the default RNG in R is the Mersenne-Twister.

```{r R MT}
RNGkind("Mersenne-Twister")
set.seed(12345)
rnorm(2)
```

```{python Py base}
import random
random.seed(12345)

random.normalvariate(0, 1)
```


```{python Py MT}
import numpy as np
from numpy.random import Generator, RandomState, SeedSequence, MT19937, PCG64

ss = SeedSequence(12345)
mt_rs = RandomState(MT19937(ss))
mt_rs.standard_normal(1)

mt_gen = Generator(MT19937(ss))
mt_gen.standard_normal(1)
```


```{r R pcg}
library(dqrng)
dqRNGkind("pcg64")

dqset.seed(12345)
dqrnorm(1)
```

```{python Py pcg}
ss = SeedSequence(12345)

pcg_rs = RandomState(PCG64(ss))
pcg_rs.standard_normal(1)

pcg_gen = Generator(PCG64(ss))
pcg_gen.standard_normal(1)
```


```{r using SyncRNG R}
library(SyncRNG)

rng <- SyncRNG(seed=12345)

N <- 20
resampled.idx <- vector(length = N)

for (i in 1:N) {
  resampled.idx[i] <- rng$randbelow(N)
}

resampled.idx
```



```{python using SyncRNG Python}

def bootstrap_sample(sample, seed=12345):
    from SyncRNG import SyncRNG as sync_rng
    import numpy as np
    
    rng = sync_rng(seed)
    samp = np.array(sample)
    N = len(samp)
  
    resampled_idx = np.zeros(N, dtype=int)

    for i in range(N):
        resampled_idx[i] = rng.randbelow(N)
        
    return(samp[resampled_idx])
    
```



